version: '3'

services:

  # certbot:
  #   image: certbot/certbot:v1.4.0
  #   volumes:
  #     - ./volumes/letsencrypt:/etc/letsencrypt
  #   ports: 
  #     - 80:80
  #   entrypoint: "certbot certonly --non-interactive --test-cert --agree-tos -m ${ADMIN_EMAIL} --standalone -d ${BASE_DOMAIN}"

  postgresql:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASS}
      POSTGRES_DB: ${SQL_BASE}
    volumes: 
      - ./volumes/db:/var/lib/postgresql/data

  hmdm:
    image: headwindmdm/hmdm:0.1.0
    ports:
      - 443:8443
      - 8080:8080
      - 31000:31000
    volumes:
      - ./volumes/work:/usr/local/tomcat/work
      # - ./volumes/letsencrypt:/etc/letsencrypt
    environment:
      SQL_HOST: postgresql
      SQL_USER: ${SQL_USER}
      SQL_BASE: ${SQL_BASE}
      SQL_PASS: ${SQL_PASS}
      BASE_DOMAIN: ${BASE_DOMAIN}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      HMDM_VARIANT: ${HMDM_VARIANT}
      DOWNLOAD_CREDENTIALS: ${DOWNLOAD_CREDENTIALS}
      HMDM_URL: ${HMDM_URL}
      CLIENT_VERSION: ${CLIENT_VERSION}
      PROTOCOL: ${PROTOCOL}

